=== frendy73/XML/2/notebook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="notebook">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="offices" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="office" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="person" minOccurs="1" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string"/>
                          <xs:element name="address" type="xs:string"/>
                          <xs:element name="phones">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="phone" minOccurs="0" maxOccurs="unbounded">
                                  <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                      <xs:pattern value="\d{3}-\d{2}-\d{2}"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                        <xs:attribute name="office" type="xs:IDREF" use="required"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="code" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== frendy73/XML/2/notebook.xml
<?xml version="1.0"?>
<notebook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="notebook.xsd">
    <offices>
        <office code="OF001">
            <person id="P001" office="OF001">
                <name>John Doe</name>
                <address>1234 Some Street, Some City</address>
                <phones>
                    <phone>123-45-67</phone>
                </phones>
            </person>
        </office>
    </offices>
</notebook>
